In [ ]:
import pandas as pd
df=pd.read_csv("/content/BMI.csv")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/BMI.csv'

In [ ]:
df.shape

NameError: name 'df' is not defined

In [ ]:
df.info()

In [ ]:
df.describe()

In [ ]:
df.isna().sum()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
df.head()

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Gender']=le.fit_transform(df['Gender'])
print(df.head())

x=df[['Gender','Height','Weight']]
y=df.Index

from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.2,random_state=1)

NameError: name 'df' is not defined

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=5,metric='euclidean')  #k value
knn.fit(xtrain,ytrain)

In [ ]:
ypred=knn.predict(xtest)
print(ypred)

In [ ]:
from sklearn.metrics import classification_report,accuracy_score
print(accuracy_score(ytest,ypred))

In [ ]:
print(classification_report(ytest,ypred))

##Hands on Linear SVM

In [ ]:
import pandas as pd
data = pd.read_csv("/content/apples_and_oranges.csv")
data.head()

   Weight  Size   Class
0      69  4.39  orange
1      69  4.21  orange
2      65  4.09  orange
3      72  5.85   apple
4      67  4.70  orange

In [ ]:
data.shape

(40, 3)

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Weight  40 non-null     int64
 1   Size    40 non-null     float64
 2   Class   40 non-null     object
dtypes: float64(1), int64(1), object(1)
memory usage: 1.1+ KB

In [ ]:
data.describe()

          Weight       Size
count  40.000000  40.000000
mean   70.200000   4.922750
std     3.039906   0.590063
min    65.000000   4.010000
25%    68.000000   4.360000
50%    70.000000   4.930000
75%    73.000000   5.472500
max    75.000000   5.850000

In [ ]:
data.isnull().sum()

Weight    0
Size      0
Class     0
dtype: int64

###Treating Categorial Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
data.Class = le.fit_transform(data.Class)
data.head()

   Weight  Size  Class
0      69  4.39      1
1      69  4.21      1
2      65  4.09      1
3      72  5.85      0
4      67  4.70      1

###Sampling the Dataset

In [ ]:
from sklearn.model_selection import train_test_split
x=data[['Weight','Size']]
y=data.Class
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

###Building the Linear SVC Classifier

In [ ]:
import warnings
warnings.simplefilter("ignore")
from sklearn.svm import LinearSVC
classifier = LinearSVC()
classifier.fit(x_train,y_train)

LinearSVC()

###Calculating Test accuracy

In [ ]:
from sklearn.metrics import accuracy_score
y_pred = classifier.predict(x_test)
print("Test Accuracy=",accuracy_score(y_test,y_pred))

Test Accuracy= 1.0

###Confusion Matrix

In [ ]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_test,y_pred))

[[2 0]
 [0 6]]

##Hands on for NON Linear SVM

In [ ]:
import pandas as pd
df = pd.read_csv("/content/Iris.csv")
df.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [ ]:
df.shape

(150, 6)

In [ ]:
df.describe()

               Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [ ]:
df.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

###Build Multiclass Linear & Non-Linear Models

In [ ]:
from sklearn.svm import LinearSVC, SVC
x = df.iloc[:,0:5]
y = df.Species

lin_svc = LinearSVC().fit(x,y)

# svc with linear kernel
svc_lin = SVC(kernel='linear').fit(x,y)
# the linear kernel assumes linear decision boundary

# svc with RBF kernel
rbf_svc = SVC(kernel='rbf').fit(x,y)

poly_svc3 = SVC(kernel='poly',degree=3).fit(x,y)

poly_svc4 = SVC(kernel='poly',degree=4).fit(x,y)

###Printing all the model scores

In [ ]:
print("SVC Linear Score:",svc_lin.score(x,y))
print("RBF SVC Score:",rbf_svc.score(x,y))
print("3 Degree Polynomial SVC Score:",poly_svc3.score(x,y))
print("4 Degree Polynomial SVC Score:",poly_svc4.score(x,y))

SVC Linear Score: 1.0
RBF SVC Score: 1.0
3 Degree Polynomial SVC Score: 0.9733333333333334
4 Degree Polynomial SVC Score: 0.96